Try to commit 1st HW again
Tiloaria/AU_Java_2017 pull request #2
Opened 2017-09-26 23:47 UTC by Tiloaria

I needed to remove my first branch with HW1 and create new.

2017-10-04 14:29 UTC, jzuken requested changes

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
этот файлик тут не нужен, мне кажется

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +public class HashTable {
а где джавадок к классу? -1 балл

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +            if(next.key == findKey)
после if по стайлгайду пробел надо

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +    private class Element {
приватные вложенные классы лучше помещать в конец класса

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +    private Element [ ] table = new Element[places]; //table with links to first elements
тут с пробелами тоже что-то странное

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +        if (curentElement == null || curentElement.contains(key) == null) {
за такое я обещал аж два балла снимать (строчка 14 тут: https://docs.google.com/spreadsheets/d/1gkW7xzlsf8WocpJIcIZGmPCfv7czdEilR_QjfpH7zhI/edit#gid=0). на первый раз сниму один, но не надо так писать, пожалуйста

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +        if(table[place] == null)
пробел

2017-10-04 14:29 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +        if(findElement != null)
и тут тоже пробелы. ещё -0.5 балла за стайлгайд

2017-10-04 19:45 UTC, Tiloaria commented
Ошибки исправлены.

2017-10-07 16:00 UTC, jzuken requested changes

2017-10-07 16:00 UTC, jzuken commented on HW1_HashTable/HashTable.java
> +    private Element [ ] table = new Element[places]; //table with links to first elements
всё ещё не исправлено, два лишних пробела
-0.5

2017-11-26 17:37 UTC, jzuken commented
с учётом продолбанных сроков 6 баллов. не затягивайте, пожалуйста, с остальными задачами

2017-11-26 17:37 UTC, merged