HW2_Spiral added
Tiloaria/AU_Java_2017 pull request #4
Opened 2017-09-27 20:26 UTC by Tiloaria

2017-10-07 15:10 UTC, jzuken requested changes

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
эти файлы давно пора было добавить в .gitignore
-1 балл

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/src/main/java/Spiral.java
> +public class Spiral {
ко всем публичным классам у нас требуется писать доки

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/src/main/java/Spiral.java
> +    public Spiral(int new_size, int [] [] new_matrix) {
стайлгайд, -0.5 балла

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/src/main/java/Spiral.java
> +
пустая строка лишняя

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/src/main/java/Spiral.java
> +     * @return
тут что-то странное, тег пустой

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/src/test/java/SpiralTest.java
> +    public void  SetUp(){
лишний пробел, имя с заглавной буквы

2017-10-07 15:10 UTC, jzuken commented on HW2_Spriral/src/test/java/SpiralTest.java
> +public class SpiralTest {
по одному тесту это как-то маловато, особенно с сортировкой. там можно много всяких случаев проверить

2017-10-07 15:15 UTC, jzuken commented
и, кстати, у меня тесты не проходят:
SpiralTest > sort FAILED
    java.lang.NullPointerException at SpiralTest.java:56

SpiralTest > getSpiral FAILED
    java.lang.NullPointerException at SpiralTest.java:35

если внимательно посмотрите на вашу функцию SetUp(), то поймёте почему
-1 балл

2017-12-12 23:42 UTC, Tiloaria commented
Тесты которые были проходили, не увидела проблемы.

2017-12-23 07:11 UTC, jzuken requested changes

2017-12-23 07:11 UTC, jzuken commented on HW2_Spriral/src/main/java/Spiral.java
> +    public Spiral(int new_size, int[][] new_matrix) {
ну параметры как именовались не по стайлгайду, так и продолжают :(
-1

2017-12-23 07:11 UTC, jzuken commented on HW2_Spriral/src/test/java/SpiralTest.java
> +    Spiral spiralOwn;
хоть это и тест, лучше всё равно делать поля private

2017-12-23 07:11 UTC, jzuken commented on HW2_Spriral/src/test/java/SpiralTest.java
> +     * @throws Exception
не надо оставлять таких "висячих" комментариев. они не добавляют ничего коду, при этом занимают место и выглядят уродливо

2017-12-23 07:11 UTC, jzuken commented on HW2_Spriral/src/test/java/SpiralTest.java
> +        ArrayList<Integer> five = new ArrayList<>();
лучше разбить на несколько тестов, каждый из которых проверяет что-то своё и что-то одно (и называется соответсвующе)

2017-12-23 07:13 UTC, jzuken commented
и теперь тесты проходят, кстати. вы же раньше в SetUp() локальную переменную создавали, как оно могло работать?

2017-12-26 10:28 UTC, merged